spring:
  sql:
    init:
      mode: embedded
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
